### ISSUE TITLE
Location search on home page not working

### ISSUE THREAD

**Issue by joepio** [openstate/poliflw#35]
When I enter `Utrecht` in the bottom search bar, the URL changes to `https://poliflw.nl/?location=Utrecht`.
It should link to `https://poliflw.nl/zoeken?location=Utrecht`.
In other words, the string should contain `zoeken.`

**Comment by breyten** [comment]
Hmmm on what browser? (also, a shift+reload might help)

In any case, [the code](https://github.com/openstate/poliflw/blob/master/app/frontend/static/scripts/app.js#L107) seems ok, but I think you might not be getting the correct JS attach to it. Are you seeing typeahead suggestions?

**Comment by joepio** [comment]
Tested on latest chrome, latest firefox, latest safari. Same behavior on all browsers.

The Typeahead suggestions appear, but I didn't notice them earlier, since I just typed in the name and pressed enter. The buggy behavior only seems to occur when I press enter, not when I click.

**Comment by breyten** [comment]
Ah, yes I thought the typeahead plugin would catch this as well. So it'll now forward to whatever you type in the correct way. Thanks for letting us know!
